---
title: "RNome MSRseq tRNAmod"
author: "Luke R Frietze, Hoang-Anh Tran"
date: "2/12/2026"
output: html_document
editor_options: 
  chunk_output_type: console
---

#READ ME
```{r}
#Script: RNome_MSRseq_tRNAmod.Rmd
# Description:
# Converts modification data generated by the pipeline described in previous works, 10.1016/bs.mie.2024.11.009, and converts it into a single excel which can be used in the bedRmod_format_converter.Rmd script. 

# Built with:
#   R version 4.2.2 (2022-10-31)

# Package versions:
#   tidyverse 2.0.0
#   dplyr      1.1.3


# Input:
#   Modification data output from the predefined MSRseq pipeline as defined in 10.1016/bs.mie.2024.11.009.

# Output:
#   data_cleaned_5_HRPC.csv.zip which is a compressed excel of all modification rates and positions for all sequenced isodecoder positions

# Author:
#   Hoang-Anh Tran, Luke R Frietze

# Date:
#   2026-2-12

# ============================================================

```


#Set up packages
```{r, set up packages etc., echo=FALSE, results="hide", warning=FALSE, message=FALSE}
#Import packages for plotting and data manipulation.
library(tidyverse)
library(dplyr)

#Define a function that excludes things
`%nin%` = Negate(`%in%`)
```

#data_cleaner
##Clean data for further analysis
```{r}
# This function is designed to clean the data so that it can be used in the rest of the script. You will probably have to change this for specifications of your data handling.

#' @param PATH a string which is the relative path from the set working directory to the file being cleaned
#' @return a list which holds the cleaned data

data_cleaner <- function(PATH) {
print(getwd())
PATH
FILES <- data.frame( file_name = list.files(PATH) ) %>%
  filter(!grepl("unassigned",file_name),
         file_name %nin% c("kallisto.out", "kallisto.err")
         )

# ***USER INPUT NEEDED***
# Split generic file names into salient parts
# Specify your file name formula. Indicate which parts are "library", "barcode", "bin_start", "bin_stop".
# For information that you do not need, name the part to contain "junk".
# IMPORTANT! Make sure the "library" and the "barcode" section is unique for each sample.
FILES <- FILES %>%
  separate(file_name, 
           sep="_", c("library", "junk1", "junk2", "junk3",
                      "barcode", "junk4",
                      "bin_start", "bin_stop",
                      "junkmore"),
           fill="right", remove=FALSE) %>%
  select(-matches("junk"))




### ***USER INPUT NEEDED***
# Create a dataframe where you define the files that you want to analyze
# only for the barcodes/indexes you are interested in
# Include the following columns:
## Index (corresponding to the "library" above)
## Barcode (e.g. bc1, bc2, etc., corresponding to the "barcode" above)
## Treatment (what is your experimental treatments)
## Rep (replicate number)

namelist_master <- data.frame(
  Index = c(rep("TP-AB-19s-R-Con", 3), rep("TP-AB-19s-R-BS", 3), rep("TP-AB-19s-R-CBH", 3)),
  Barcode = rep(c("bc8", "bc9", "bc10"), 3),
  Treatment = c(rep("HRPC_ctrl", 3), rep("HRPC_BS", 3), rep("HRPC_CBH", 3)),
  Rep = rep(1:3, 3)
)


#DONT TOUCH
FILES <- FILES %>%
  inner_join(namelist_master, 
             by = c("library" = "Index",
                    "barcode" = "Barcode")) %>%
  select(-library, -barcode) %>%
  rename(treatment = Treatment,
         rep = Rep)


##### end of part you will have to change extensively
#NO MORE USER INPUT REQUIRED BEYOND THIS POINT 

FILES$file_name <- as.character(FILES$file_name)
FILES <- FILES %>%
  filter(rep != "remove")
#=======================+
FILES <- FILES %>%
  mutate(bin_start = ifelse(is.na(bin_start), -3, bin_start),
         bin_stop = ifelse(is.na(bin_stop), -3, bin_stop))
#========================

read_in_one <- function(row){
  output <- read.csv(paste0(PATH, row$file_name), header=T, sep="\t") %>%
    mutate(rep = row$rep,
           treatment = row$treatment,
           bin_start = row$bin_start,
           bin_stop  = row$bin_stop,)
  #specify data types since empty dataframes get confused and sad
  if (grepl("5_tsv", PATH)) {
    output$gene <- as.character(output$gene)
  output$base <- as.character(output$base)
  return(output)
  } else {
  output$name <- as.character(output$name)
  output <- output %>%
    mutate(gene=name) %>%
    select(-name)
  return(output)
  }
}

Ecoli_charging_counts_data <- FILES %>%
  group_by(file_name) %>%
  do(read_in_one(.)) %>%
  ungroup() 


#seperate the gene so can have different column names
final_data <- Ecoli_charging_counts_data %>%
  mutate(source = ifelse(grepl("mt", gene), "mitochondrial", "cytosolic")) %>%
  #mutate(source = ifelse(grepl("_", gene), "cytosolic", "mitochondrial")) %>%
  separate(gene, sep="-", c("junk1","AA", "anticodon","junk2", "junk3"), fill="right", remove=FALSE) %>%
  select(-junk1, -junk2, -junk3) %>%
  mutate(
    AA = ifelse(source == "mitochondrial", str_extract(gene, "(?<=mt)\\w{3}"), AA),
    anticodon = ifelse(source == "mitochondrial", str_sub(gene, -3), anticodon)
  )
  
  #this chunk is for handeling other Meso-RNA in the sample besides tRNA if u want them excluded then take out this
  final_data <- final_data %>%
  mutate(gene = ifelse(is.na(anticodon), str_replace(gene, ".*_", ""), gene),
  AA = ifelse(is.na(anticodon), "Meso", AA),
  anticodon = ifelse(is.na(anticodon), gene, anticodon))

#change gene name
final_data <- final_data %>%
  mutate(gene = str_replace(gene, ".*tRNA-", "")) %>%
  na.omit(select = c(AA, anticodon))

 return(final_data)

}
```

#Data Cleaning Main Dashboard
```{r}
#makes the data frames that are needed for everything else
#data_cleaned_6 <- data_cleaner("6_sam_counter\\Step1_260_seq_hg38-mature-tRNAs_renamed\\")
data_cleaned_5 <- data_cleaner("5_tsv\\Step1_260_seq_hg38-mature-tRNAs_renamed\\")
write.csv(data_cleaned_5,
          "data_cleaned_5_HRPC.csv")
zip("data_cleaned_5_HRPC.csv.zip",
    "data_cleaned_5_HRPC.csv")
```
